apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sistema-notas
resources:
  - deploy_sistema_nota_api.yaml
  - mysql-infra.yaml   
images:
  - name: emeday17/sistema-notas-api
    newTag: "0.4"
