apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sistema-notas
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - services/iam/deploy-svc.yaml
  - services/personas/deploy-svc.yaml
  - services/cursos/deploy-svc.yaml
  - services/evaluaciones/deploy-svc.yaml
  - services/db_mysql
  - ingress/ingress.yaml
