apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sistema-notas
resources:
  - ../../base
images:
  - name: emeday17/sistema-notas-iam
    newTag: "1.0.0"
  - name: emeday17/sistema-notas-personas
    newTag: "1.0.0"
  - name: emeday17/sistema-notas-cursos
    newTag: "1.0.0"
  - name: emeday17/sistema-notas-evaluaciones
    newTag: "1.0.0"
